name: publish

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["GSRI_Entrainement.Altis/**"]

jobs:
  release:
    runs-on: [self-hosted, arma-tools]
    steps:
      - name: Make mission pbo
        uses: team-gsri/actions-arma-tools/release-mission@v0
        with:
          missionName: Entrainement
          source: ./GSRI_Entrainement.Altis
